name: lamp
channels:
  - pytorch
  - defaults
  - nvidia
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cudatoolkit=11.6.0
  - ffmpeg=4.3
  - freetype=2.11.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - intel-openmp=2021.4.0
  - jpeg=9d
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - ninja=1.10.2
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openh264=2.1.0
  - openssl=1.1.1l
  - pillow=8.4.0
  - pip=21.2.4
  - ppython=3.9.7
  - python_abi=3.8
  - readline=8.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - torchvision=0.11.1
  - wheel=0.37.0
  - x264=1!157.20191217
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - arrow==1.2.2
    - async-timeout==4.0.1
    - attrs==21.2.0
    - boto3==1.20.45
    - botocore==1.23.45
    - bravado==11.0.3
    - bravado-core==5.17.0
    - charset-normalizer==2.0.9
    - click==8.0.3
    - datasets==1.16.1
    - dill==0.3.4
    - filelock==3.4.0
    - fqdn==1.5.1
    - frozenlist==1.2.0
    - fsspec==2021.11.1
    - future==0.18.2
    - gitdb==4.0.9
    - gitpython==3.1.26
    - huggingface-hub==0.2.1
    - idna==3.3
    - isoduration==20.11.0
    - jmespath==0.10.0
    - joblib==1.1.0
    - jsonpointer==2.2
    - jsonref==0.2
    - jsonschema==4.4.0
    - monotonic==1.6
    - msgpack==1.0.3
    - multidict==5.2.0
    - multiprocess==0.70.12.2
    - nltk==3.6.5
    - numpy==1.21.4
    - oauthlib==3.1.1
    - packaging==21.3
    - pandas==1.3.5
    - pillow==9.0.0
    - psutil==5.9.0
    - pyarrow==6.0.1
    - pyjwt==2.3.0
    - pyparsing==3.0.6
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyyaml==6.0
    - regex==2021.11.10
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rfc3339-validator==0.1.4
    - rfc3987==1.3.8
    - rouge-score==0.0.4
    - s3transfer==0.5.0
    - sacremoses==0.0.46
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - simplejson==3.17.6
    - sklearn==0.0
    - smmap==5.0.0
    - swagger-spec-validator==2.7.4
    - threadpoolctl==3.0.0
    - tokenizers==0.10.3
    - tqdm==4.62.3
    - transformers==4.14.1
    - typing-extensions==4.0.1
    - uri-template==1.1.0
    - urllib3==1.26.7
    - webcolors==1.11.1
    - websocket-client==1.2.3
    - xxhash==2.0.2
    - yarl==1.7.2